# Generated by Django 3.2.9 on 2021-11-25 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_open_date',
            field=models.DateField(default=datetime.date(2021, 11, 25)),
        ),
    ]
