# Generated by Django 3.2.9 on 2021-11-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_listing_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='username',
            field=models.CharField(default='AnonymourUser', max_length=80),
            preserve_default=False,
        ),
    ]
