# Generated by Django 3.2.9 on 2021-11-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listingitem',
            new_name='l_item',
        ),
        migrations.AddField(
            model_name='bid',
            name='l_name',
            field=models.CharField(default='Listing_NUll', max_length=60),
            preserve_default=False,
        ),
    ]
