# Generated by Django 3.2.9 on 2021-11-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20211125_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='c_price',
            field=models.FloatField(default=models.FloatField()),
        ),
    ]
