# Generated by Django 3.2.9 on 2021-11-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_c_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=80)),
                ('usern', models.CharField(max_length=80)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='c_bidder',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='listing',
            name='c_price',
            field=models.FloatField(default=0.0),
        ),
    ]
