# Generated by Django 3.2.9 on 2021-11-25 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20211125_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=80)),
                ('item_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_open_date',
            field=models.DateField(default=datetime.date(2021, 11, 26)),
        ),
    ]
