# Generated by Django 3.2.9 on 2021-12-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_liked_by',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
