# Generated by Django 3.2.9 on 2021-12-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.CharField(max_length=400)),
                ('following_accout', models.CharField(max_length=400)),
            ],
        ),
    ]
