# Generated by Django 3.2.9 on 2021-12-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following_accout',
            new_name='following_account',
        ),
    ]
