# Generated by Django 3.2.9 on 2021-11-24 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='date',
            field=models.DateField(default=datetime.date(2021, 11, 24)),
        ),
        migrations.AlterField(
            model_name='listings',
            name='c_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='picture',
            field=models.URLField(null=True),
        ),
    ]
