# Generated by Django 3.2.9 on 2021-11-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211124_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
