# Generated by Django 3.2.9 on 2021-11-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20211124_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='c_price',
            field=models.FloatField(default=models.FloatField()),
        ),
    ]
