# Generated by Django 3.2.9 on 2021-11-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listings_c_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='c_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
