# Generated by Django 3.2.9 on 2021-11-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listings_c_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='c_price',
        ),
    ]
