# Generated by Django 3.2.9 on 2021-11-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listings_c_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='c_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
